AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false
