AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'spec/**/*'

Metrics/LineLength:
  Max: 80
  IgnoredPatterns: ['\A\s*#']

Metrics/MethodLength:
  Exclude:
    - 'db/**/*'

Security/Open:
  Exclude:
    - 'app/queries/participant_from_oauth.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/StructInheritance:
  Exclude:
    - 'spec/**/*'
